// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLoveLoverRelation = "love_lover_relation"

// LoveLoverRelation mapped from table <love_lover_relation>
type LoveLoverRelation struct {
	ID            int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`    // id
	User1ID       string `gorm:"column:user1_id;not null;comment:user1_id" json:"user1_id"`       // user1_id
	User2ID       string `gorm:"column:user2_id;not null;comment:user2_id" json:"user2_id"`       // user2_id
	User1Nickname string `gorm:"column:user1_nickname;not null;comment:昵称" json:"user1_nickname"` // 昵称
	User2Nickname string `gorm:"column:user2_nickname;comment:昵称" json:"user2_nickname"`          // 昵称
}

// TableName LoveLoverRelation's table name
func (*LoveLoverRelation) TableName() string {
	return TableNameLoveLoverRelation
}
