// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLoveUserInfo = "love_user_info"

// LoveUserInfo mapped from table <love_user_info>
type LoveUserInfo struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`       // id
	OpenID     string `gorm:"column:open_id;not null;comment:openId" json:"open_id"`              // openId
	SessionKey string `gorm:"column:session_key;not null;comment:会话密钥" json:"session_key"`        // 会话密钥
	UnionID    string `gorm:"column:union_id;comment:微信开放平台唯一标识（可选，如果需要跨应用统一用户）" json:"union_id"` // 微信开放平台唯一标识（可选，如果需要跨应用统一用户）
	Nickname   string `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                // 昵称
	Name       string `gorm:"column:name;not null;comment:名称" json:"name"`                        // 名称
	Gender     int32  `gorm:"column:gender;comment:用户性别（0表示未知，1表示男性，2表示女性）" json:"gender"`        // 用户性别（0表示未知，1表示男性，2表示女性）
	Tel        int32  `gorm:"column:tel;comment:绑定手机号" json:"tel"`                                // 绑定手机号
	AvatarURL  string `gorm:"column:avatar_url;comment:用户头像url" json:"avatar_url"`                // 用户头像url
}

// TableName LoveUserInfo's table name
func (*LoveUserInfo) TableName() string {
	return TableNameLoveUserInfo
}
